# Generated by Django 4.1.5 on 2023-07-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="pedidos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("fecha", models.DateField()),
                ("enviado", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="productos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("categoria", models.CharField(max_length=40)),
                ("precio", models.IntegerField()),
                ("proveedor", models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("pais", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=10)),
            ],
        ),
    ]
