# Generated by Django 4.1.5 on 2023-07-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("ciudad", models.CharField(max_length=30)),
                ("carrera", models.CharField(max_length=30)),
            ],
        ),
    ]
